services:
  - type: web
    name: render-app
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y wget unzip curl gnupg
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      apt install -y ./google-chrome-stable_current_amd64.deb
      pip install -r requirements.txt
    startCommand: python flask-app.py
    envVars:
      - key: GOOGLE_CHROME_BIN
        value: /usr/bin/google-chrome
